name: '每日一句'

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 1-23 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install'
      run: python -m pip install --upgrade requests pyaes
    - name: 'requirements'
      run: pip install -r requirements.txt  
    - name: 'Run'
      env:
        SEND_KEY: ${{ secrets.SEND_KEY }}
      run: python main.py
